# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Surbhi Singh
title: Software Engineer
email: surbhi93930@gmail.com
#website: https://github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  surbhi930
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: surbhi-04
instagram_username: surbhi_04
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Surbhi Singh and I'm a software engineer with over 5 years experience in backend development.
  I am currently working at Teradata on their orchestration tool for Data streaming, backup and restore, called DTU.
  
  With five years of experience, including two years at an R&D lab, 
  I have gained a solid understanding of database systems and conducting research. 
  I am eager to further my knowledge and delve deeper into these areas through a comprehensive research program. 
  My research interests lie in database systems, programming language, and machine learning. 

content:
  - title: Research Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Teradata R&D Labs
        link: https://www.teradata.com/Products/Ecosystem-Management/IntelliSphere/Data-Stream-Architecture
        link_text: Check the project here
        sub_title: Software Engineer
        caption: April 2021 - Present
        quote: >
          DTU is an orchestration tool that provides migration of the entire Teradata Database Ecosystem 
          both for on premises to on premises and for on premises to cloud configurations.
        description: | # this will include new lines to allow paragraphs
          Currently working as an R&D Engineer in building data migration tools. 
          
          Led the development of Incremental backup & restore features and Dictionary only migration to reduce migration downtime.
          Implemented online system migration capability and pause and resume functionality.
          Developed a downtime estimator tool to give an estimate of the migration to the customers in advance of the actual migration happening. 
          This helps the customers to plan downtime in advance.
          
          Gathered customer feedback and proposed a solution to implement Dictionary level migration in a hackathon. 
          The prototype was selected in Top 5.
          Trained and mentored junior programmers in programming methodologies and best practices.

      - layout: left
        title: CDAC, Pune
        link: https://www.cdac.in/index.aspx?id=mc_st_speech_technology
        link_text: Check the project here
        sub_title: Research Assistant
        caption: July 2017 - June 2018
        quote: >
          Automatic Speech Recognition model. It converts speech to text and supports local Indian language, dialect and accent.
        description: | # this will include new lines to allow paragraphs
          Assisted in a research project of training Speech Recognition models for various Indian languages.
          Led data collection effort to gather audio data in different Indian languages for the speech recognition model.
          
          Developed a web-based speech recording tool to collect audio data in different Indian languages of different profiles. 
          Implemented algorithms to efficiently store and process large audio and text files. These tools were used by teams at CDAC to train their ASR model.

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Automatic Speech Recognition, Ease of typing
        link: https://www.ijraset.com/fileserve.php?FID=16093
        link_text: Read Paper Here
        additional_links:
          - title: Read Paper Here
            icon: fas fa-globe
            url: https://www.ijraset.com/fileserve.php?FID=16093
        sub_title: Journal IJRASET International Journal for Research in Applied Science & Engineering Technology

  - title: Research Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Web based Speech Recording Tool
        link: https://www.cdac.in/index.aspx?id=mc_st_Speech_Recognition
        link_text: CDAC Speech Technology
        additional_links:
          - title: CDAC Speech Recognition
            icon: fas fa-globe
            url: https://www.cdac.in/index.aspx?id=mc_st_Speech_Recognition
        description: | # this will include new lines to allow paragraphs
          ASR (Automatic Speech Recognition) System for Hindi, Bangla, Marathi, and Malayalam.
          
          Developed a web-based speech recording tool to collect audio data in different Indian languages of different profiles.
          Implemented algorithms to efficiently store and process large audio and text files. 
          These tools were used by teams at CDAC to train their ASR model.

          Built an application to sort and store profile information of speakers such as gender, age, mother tongue, etc. 
          The metadata of the speaker is used in training automatic speech recognition tools.

  - title: Software Development Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Verizon
        link: https://www.verizon.com/
        # link_text: boringcompany.com
        sub_title: Member of Technical Staff
        caption: January 2020 - February 2021
        quote: >
          Telecommunication billing system for postpaid customers of Verizon account.
        description: | # this will include new lines to allow paragraphs
          Awarded Verizon Innovation Award for successfully delivering two projects at once.
          
          Developed a usage based billing system for postpaid customers of Verizon. Extended the system to support IOT. 
          Rates the data, sms, mms, and voice usages of the customers with postpaid plans.
          Migrated legacy code to new code base using Java 1.8, Spring Boot, Oracle SQL Developer, Cassandra.
          
          Automated the testing by developing an XML comparison tool. 
          It reduced manual tasks by 80% and ensured minimal-defect code by comparing new code and legacy code response.

          Worked on development of new features and enhancements to generate an account list at different levels 
          at the end of each billing cycle by using cron jobs.

      - layout: left
        title: Tata Consultancy Services
        sub_title: Assistant System Engineer
        caption: January 2020 - February 2021
        description: | # this will include new lines to allow paragraphs
          Provisioning platform, Container as a Service for Nokia Customers using Java and Spring Boot where CI/CD pipelines
          are created based on project development templates with all necessary tools that a developer needs for working on the containerized applications & scripts.
          Automated cloud tasks using Java & Rest APIs for Nokia developers to ease out mundane development tasks.
          
          Conducted an eight-week training program to coach a team of entry-level in programming languages Java, Python, SQL and help them ease their transition to industry career. 
          
          Led a 5-person team to develop an employee performance tracker. 
          It helps the managers to automate the tedious task and also has interesting features like projects delivered, leaves taken, birthday reminders, certifications, etc.

  - title: Certifications & Courses
    layout: text
    content: | # this will include new lines to allow paragraphs
      - AWS Certified Solution Architect - Associate
      - Oracle Certified Associate, Java SE 8 Programmer
      - Certified SAFe 5 Practitioner - Scaled Agile
#- Mathematics for Data Science & Machine Learning - DeepLearning

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Bharati Vidyapeeth University, Pune
        caption: 9.54 CGPA | 2014 - 2018
        sub_title: BTech, Information Technology

  - title: Skills # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      - Java 8, Python, Data Structures, Algorithms, RDBMS, SQL, REST API
      - Web Services, OOP, Database Systems, Database Migration Technologies
      - Machine Learning, Linear Algebra, Calculus

  - title: Awards & Achievements
    layout: text
    content: | # this will include new lines to allow paragraphs
      - HSBC Merit Scholarship - Awarded to top students in each department in recognition of academic meritorious performance.        
      - Prime Minister Narendra Modi Scholarship - in recognition of academic meritorious performance.
      - iOEL International Olympiad of English Language 555 National Rank.

  - title: Leadership and Volunteer Work
    layout: text
    content: | # this will include new lines to allow paragraphs
      - College Music Team
      - Event Head at IT Department of College
      - Volunteer at NSS National Service Scheme
      - Volunteer at Rotaract Club of Puneâ€™s Yuva

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      During my free time, I enjoy indulging in various activities and reading, traveling, and music are my favorites.
      I have had the pleasure of visiting over 15 states within India, experiencing diverse cultures and landscapes.
      
      Presently, I am pursuing a Diploma in Hindustani Classical Music at Gandharva Mahavidyalaya. 
      In addition to music, I have discovered another creative hobby: sewing. 
      I find immense satisfaction in crafting my own clothes and 
      my ultimate aspiration is to curate a wardrobe filled with garments that I have created.
      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
